from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("student/home", views.student_home_view, name="studentHome"),
    path("student/programs/<int:program_id>", views.program_description_view, name="programDescription"),
    path("student/programs/<int:program_id>/all", views.program_tests_view, name="programTests"),
    path("student/programs/test/<int:test_id>/<int:question_count>", views.test_view, name="test"),
    path("student/programs/desc/<int:test_id>", views.test_description_view, name="testDescription"),
    path("student/progress", views.progress_view, name="progress"),
    path("student/result/<int:test_id>", views.result_view, name="result"),
    path("author/home", views.author_home_view, name="authorHome"),
    path("author/test/new", views.test_new_view, name="testNew"),
    path("author/test/<int:test_id>", views.test_created_view, name="testCreated"),
    path("author/test/delete//<int:test_id>/<int:question_id>", views.author_delete_question_view, name="deleteQuestion"),
    path("author/test/form/<int:test_id>", views.test_form_view, name="testForm"),
    path("author/programs", views.author_programs_view, name="authorPrograms"),
    path("author/programs/new", views.program_new_view, name="programNew"),
    path("author/library", views.author_library_view, name="authorLibrary"),
    path("author/library/delete/<int:test_id>", views.author_delete_test_view, name="deleteTest"),
    path("author/programs/delete/<int:program_id>", views.author_delete_program_view, name="deleteProgram"),
    path("teacher/home", views.teacher_home_view, name="teacherHome"),
    path("teacher/programs", views.teacher_programs_view, name="teacherPrograms"),
    path("teacher/programs/<int:program_id>", views.list_students_view, name="listStudents"),
    path("teacher/programs/add/<int:program_id>", views.add_student_program_view, name="addStudent"),
    path("teacher/programs/add/<int:program_id>/<int:student_id>", views.adding_student_view, name="addingStudent"),
    path("teacher/programs/delete/<int:program_id>/<int:student_id>", views.delete_student_program_view,
         name="deleteStudentProgram"),
    path("teacher/students", views.teacher_students_view, name="teacherStudents"),
    path("teacher/students/progress/<int:student_id>", views.check_student_progress_view, name="studentProgress"),
    path("teacher/students/new", views.students_new_view, name="studentNew"),
    path("teacher/students/delete/<int:student_id>", views.students_delete_view, name="studentDelete"),
]